package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/odysseia-greek/attike/euripides/graph/model"
)

// Trace is the resolver for the trace field.
func (r *queryResolver) Trace(ctx context.Context, id string) (*model.Trace, error) {
	traceResponse, _ := r.Handler.TraceById(ctx, id)

	return traceResponse, nil
}

// Traces is the resolver for the traces field.
func (r *queryResolver) Traces(ctx context.Context, rangeArg model.TimeRangeInput, filter *model.TraceFilterInput, orderBy *model.TraceOrderBy, orderDir *model.OrderDirection, page *model.PaginationInput) (*model.TracePage, error) {
	panic(fmt.Errorf("not implemented: Traces - traces"))
}

// Metrics is the resolver for the metrics field.
func (r *queryResolver) Metrics(ctx context.Context, rangeArg model.TimeRangeInput, scope *model.MetricScopeInput, resolution *model.MetricResolution, groupBy *model.MetricGroupBy, orderBy *model.MetricOrderBy, orderDir *model.OrderDirection, page *model.PaginationInput) (*model.MetricSeriesPage, error) {
	panic(fmt.Errorf("not implemented: Metrics - metrics"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
