package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/odysseia-greek/attike/euripides/graph/model"
)

// Trace is the resolver for the trace field.
func (r *queryResolver) Trace(ctx context.Context, id string) (*model.Trace, error) {
	return r.Handler.TraceById(ctx, id)
}

// TracePoll is the resolver for the tracePoll field.
func (r *queryResolver) TracePoll(ctx context.Context, limit int32) (*model.EnqueueItems, error) {
	limitAsInt := int(limit)
	return r.Handler.TracePoll(ctx, &limitAsInt)
}

// TraceSearch is the resolver for the traceSearch field.
func (r *queryResolver) TraceSearch(ctx context.Context, input model.TraceSearchInput) (*model.TracePage, error) {
	return r.Handler.TraceSearch(ctx, &input)
}

// Metrics is the resolver for the metrics field.
func (r *queryResolver) Metrics(ctx context.Context, rangeArg model.TimeRangeInput, scope *model.MetricScopeInput, resolution *model.MetricResolution, groupBy *model.MetricGroupBy, orderBy *model.MetricOrderBy, orderDir *model.OrderDirection, page *model.PaginationInput) (*model.MetricSeriesPage, error) {
	panic(fmt.Errorf("not implemented: Metrics - metrics"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
