apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: odysseia
deploy:
  kubeContext: k3d-odysseia
  tolerateFailuresUntilDeadline: true

build:
  local:
    push: false

profiles:
  - name: aristophanes
    build:
      artifacts:
        - image: ghcr.io/odysseia-greek/aristophanes
          context: ./aristophanes
          docker:
            target: debug
          sync:
            manual:
              - src: '**/*.go'
                dest: '/app'
    deploy:
      helm:
        releases:
          - name: aristophanes
            chartPath: ../../odysseia-greek/mykenai/themistokles/odysseia/charts/aristophanes
            valuesFiles:
              - ../../odysseia-greek/mykenai/themistokles/odysseia/values/local.yaml
              - ../../odysseia-greek/mykenai/themistokles/odysseia/values/skaffold-values.yaml
            setValues:
              image.odysseiaapi.repo: aristophanes
