apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: odysseia
deploy:
  kubeContext: k3d-odysseia
  tolerateFailuresUntilDeadline: true
build:
  local:
    push: false
  artifacts:
    - image: ghcr.io/odysseia-greek/aiskhylos
      context: aiskhylos
      docker:
        target: prod
        buildArgs:
          project_name: aiskhylos
          TARGETOS: linux
          TARGETARCH: arm64
      sync:
        manual:
          - src: '**/*.go'
            dest: '/app'

manifests:
  rawYaml:
    - aiskhylos/infra/manifest.yaml
profiles:
  - name: dev
