// src/constants/metricsSummary.js
import gql from "graphql-tag";

export const MetricsSummaryQuery = gql`
  query metricsSummary($input: MetricsSummaryInput!) {
      metricsSummary(input: $input) {
          window
          start
          end
          nodes{
              total
              items{
                  sampleCount
                  docCount
                  node
                  cpu{
                      avg
                      max
                      p95
                      avgHuman
                      maxHuman
                      p95Human
                      totalMax
                      totalMaxHuman
                  }
                  mem{
                      avg
                      max
                      p95
                      avgHuman
                      maxHuman
                      p95Human
                      totalMax
                      totalMaxHuman
                  }
                  sortKey
              }
          }
          namespaces{
              total
              items{
                  sampleCount
                  docCount
                  namespace
                  cpu{
                      avg
                      max
                      p95
                      avgHuman
                      maxHuman
                      p95Human
                      totalMax
                      totalMaxHuman
                  }
                  mem{
                      avg
                      max
                      p95
                      avgHuman
                      maxHuman
                      p95Human
                      totalMax
                      totalMaxHuman
                  }
                  sortKey
              }
          }
          pods{
              total
              items{
                  sampleCount
                  docCount
                  podName
                  cpu{
                      avg
                      max
                      p95
                      avgHuman
                      maxHuman
                      p95Human
                  }
                  mem{
                      avg
                      max
                      p95
                      avgHuman
                      maxHuman
                      p95Human
                  }
                  sortKey
              }
          }
      }
  }
`;

