---
 # Source: sophokles/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
 name: sophokles
 namespace: odysseia
 labels:
   app: sophokles
spec:
 replicas: 1
 selector:
   matchLabels:
     app: sophokles
 template:
   metadata:
     labels:
       app: sophokles
   spec:
     serviceAccountName: sophoklessa
     containers:
       - name: "sophokles"
         image: ghcr.io/odysseia-greek/sophokles:v0.0.11
         env:
           - name: POD_NAME
             valueFrom:
               fieldRef:
                 fieldPath: metadata.name
           - name: NAMESPACE
             valueFrom:
               fieldRef:
                 fieldPath: metadata.namespace
         envFrom:
           - configMapRef:
               name: alexandros
         imagePullPolicy: Never
         ports:
           - containerPort: 50053
             name: grpc
           - containerPort: 2345
             name: delve
---
apiVersion: v1
kind: Service
metadata:
  name: sophokles
spec:
  ports:
    - port: 50053
      name: grpc
      targetPort: grpc
    - port: 2345
      name: delve
      targetPort: delve
  selector:
    app: sophokles
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sophoklessa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sophokles-access
rules:
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sophokles-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sophokles-access
subjects:
  - kind: ServiceAccount
    name: sophoklessa
    namespace: odysseia
