// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: proto/aristophanes.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TraceServiceClient is the client API for TraceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TraceServiceClient interface {
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	Chorus(ctx context.Context, opts ...grpc.CallOption) (TraceService_ChorusClient, error)
}

type traceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTraceServiceClient(cc grpc.ClientConnInterface) TraceServiceClient {
	return &traceServiceClient{cc}
}

func (c *traceServiceClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/aristophanes.TraceService/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traceServiceClient) Chorus(ctx context.Context, opts ...grpc.CallOption) (TraceService_ChorusClient, error) {
	stream, err := c.cc.NewStream(ctx, &TraceService_ServiceDesc.Streams[0], "/aristophanes.TraceService/Chorus", opts...)
	if err != nil {
		return nil, err
	}
	x := &traceServiceChorusClient{stream}
	return x, nil
}

type TraceService_ChorusClient interface {
	Send(*ParabasisRequest) error
	CloseAndRecv() (*TraceResponse, error)
	grpc.ClientStream
}

type traceServiceChorusClient struct {
	grpc.ClientStream
}

func (x *traceServiceChorusClient) Send(m *ParabasisRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *traceServiceChorusClient) CloseAndRecv() (*TraceResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(TraceResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TraceServiceServer is the server API for TraceService service.
// All implementations must embed UnimplementedTraceServiceServer
// for forward compatibility
type TraceServiceServer interface {
	HealthCheck(context.Context, *Empty) (*HealthCheckResponse, error)
	Chorus(TraceService_ChorusServer) error
	mustEmbedUnimplementedTraceServiceServer()
}

// UnimplementedTraceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTraceServiceServer struct {
}

func (UnimplementedTraceServiceServer) HealthCheck(context.Context, *Empty) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedTraceServiceServer) Chorus(TraceService_ChorusServer) error {
	return status.Errorf(codes.Unimplemented, "method Chorus not implemented")
}
func (UnimplementedTraceServiceServer) mustEmbedUnimplementedTraceServiceServer() {}

// UnsafeTraceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TraceServiceServer will
// result in compilation errors.
type UnsafeTraceServiceServer interface {
	mustEmbedUnimplementedTraceServiceServer()
}

func RegisterTraceServiceServer(s grpc.ServiceRegistrar, srv TraceServiceServer) {
	s.RegisterService(&TraceService_ServiceDesc, srv)
}

func _TraceService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraceServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aristophanes.TraceService/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraceServiceServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TraceService_Chorus_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TraceServiceServer).Chorus(&traceServiceChorusServer{stream})
}

type TraceService_ChorusServer interface {
	SendAndClose(*TraceResponse) error
	Recv() (*ParabasisRequest, error)
	grpc.ServerStream
}

type traceServiceChorusServer struct {
	grpc.ServerStream
}

func (x *traceServiceChorusServer) SendAndClose(m *TraceResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *traceServiceChorusServer) Recv() (*ParabasisRequest, error) {
	m := new(ParabasisRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TraceService_ServiceDesc is the grpc.ServiceDesc for TraceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TraceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aristophanes.TraceService",
	HandlerType: (*TraceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _TraceService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chorus",
			Handler:       _TraceService_Chorus_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/aristophanes.proto",
}
